en:
  languageName: English
  weight: 1

# zh-hans:
#   languageName: 繁體中文
#   weight: 4
#   params:
#     description: '一款基于 Hugo 和 Bootstrap 的blog'
#     keywords: 
#     archive:
#       dateFormat: 01-02
